package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastroavaliacao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouttopo.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css\" />\r\n");
      out.write("    <script src=\"https://unpkg.com/flowbite@1.5.3/dist/flowbite.js\"></script>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("    <script src=\"/path/to/cdn/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/notifier.css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <title>HRB Kids | Cadastro Avaliação </title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"grid grid-cols-0  gap-2  margin  bg-gray-50\tdark:bg-gray-800\">\r\n");
      out.write("    <script src=\"./js/notifier.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Breadcrumbs -->\r\n");
      out.write("<div class=\"flex pl-5 pt-5\" aria-label=\"Breadcrumb\">\r\n");
      out.write("    <ol class=\"inline-flex items-center space-x-1 md:space-x-3\">\r\n");
      out.write("      <li class=\"inline-flex items-center\">\r\n");
      out.write("        <a href=\"#\" class=\"inline-flex items-center  font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white\">\r\n");
      out.write("          <svg class=\"w-4 h-4 mr-2\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z\"></path></svg>\r\n");
      out.write("          Página Inicial\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <svg class=\"w-6 h-6 text-gray-400\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z\" clip-rule=\"evenodd\"></path></svg>\r\n");
      out.write("          <a href=\"#\" class=\"ml-1  font-medium text-gray-700 hover:text-gray-900 md:ml-2 dark:text-gray-400 dark:hover:text-white\">Avaliação</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <svg class=\"w-6 h-6 text-gray-400\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z\" clip-rule=\"evenodd\"></path></svg>\r\n");
      out.write("          <a href=\"#\" class=\"ml-1  font-medium text-gray-700 hover:text-gray-900 md:ml-2 dark:text-gray-400 dark:hover:text-white\">Cadastrar Avaliação </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ol>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"bg-white marginlateral pb-5 dark:bg-gray-700\">\r\n");
      out.write("  <div class=\"flex justify-between items-end responsividade\">\r\n");
      out.write("  <h3 class=\"flex pl-4 pt-5 text-4xl font-semibold text-gray-800 dark:text-white\" id=\"h3\">Avaliação\r\n");
      out.write("  </h3>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <!-- forms -->\r\n");
      out.write("<form id=\"traducao\"  method=\"POST\" action=\"/cadastraravaliacao\" accept-charset=\"UTF-8\">\r\n");
      out.write("    <div class=\"pl-4 pt-5 pr-4 grid gap-6 mb-4 md:grid-cols-3 \">\r\n");
      out.write("        <div>\r\n");
      out.write("            <label class=\"block mb-2  font-medium text-black dark:text-gray-300\">Nome do Cliente</label>\r\n");
      out.write("            <input type=\"text\" id=\"nomecliente\" name=\"nomecliente\" class=\"bg-white border border-gray-300 text-gray-900  rounded-lg focus:ring-gray-300 focus:border-gray-200 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200n-500\" placeholder=\"Ciclano da Silva\" required >\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <label class=\"block mb-2  font-medium text-black dark:text-gray-300\">Data da avaliação</label>\r\n");
      out.write("          <input  id=\"dataavaliacao\" name=\"data\" class=\"bg-white border border-gray-300 text-gray-900  rounded-lg focus:ring-gray-300 focus:border-gray-200 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200n-500\" placeholder=\"20/09/2022\" type=\"date\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<h2 class=\"flex pl-4 text-xl text-gray-400\" id=\"text\">Peças aprovadas</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<table class=\"ml-4 \">\r\n");
      out.write("  <div>\r\n");
      out.write("    <thead>\r\n");
      out.write("      <th class=\" font-medium text-black dark:text-gray-300\">Descrição</th>\r\n");
      out.write("      <th class=\" font-medium text-black dark:text-gray-300\">Quantidade</th>\r\n");
      out.write("      <th class=\" font-medium text-black dark:text-gray-300\">Preço Custo UN. (R$)</th>\r\n");
      out.write("      <th class=\" font-medium text-black dark:text-gray-300\">Preço Venda UN. (R$)</th>\r\n");
      out.write("    </div>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("      <tr id=\"tabela\">\r\n");
      out.write("         <div class=\"flex rounded-l-lg inserir \">\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"text\" id=\"descricao\" class=\"border-1 border-r-0 rounded-l-lg bg-white border-gray-300  text-gray-900 rounded-l-lg focus:ring-gray-400 focus:border-gray-400 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\" placeholder=\"Ex: Body\" required>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"number\" min=\"1\" step=\".01\" id=\"quantidade\" class=\"border-1 border-r-0 bg-white border-gray-300  text-gray-900  focus:ring-gray-400 focus:border-gray-400 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\" placeholder=\"Ex: 1\" required>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input disabled=\"disabled\" type=\"number\" id=\"valorcusto\" onblur=\"validar()\"  class= \"border-1 border-r-0 bg-gray-100 border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\"><a onblur=\"Atualizar()\"></a>\r\n");
      out.write("              </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <input type=\"text\" onblur=\"Atualizar()\"  id=\"valorvenda\" class=\"border-1 border-r-0 bg-white border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\" placeholder=\"Ex: 8,00\" required>\r\n");
      out.write("            \r\n");
      out.write("              </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <a type=\"text\" class=\"padding remove-item border-1 rounded-r-lg bg-white border-gray-300  text-gray-900  rounded-r-lg focus:ring-red-500 focus:border-red-500 block mr-5 p-2.5 dark:bg-gray-700 dark:border-red-600 dark:placeholder-gray-400 dark:text-white r-5\">\r\n");
      out.write("                  <svg  class=\"mb-1 w-6 h-5\"id=\"Camada_1\" data-name=\"Camada 1\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 18\"><defs><style>.cls-1{fill:#ed2121;}</style></defs><title>trash</title><path class=\"cls-1\" d=\"M9,3V4H4V6H5V19a2,2,0,0,0,2,2H17a2,2,0,0,0,2-2V6h1V4H15V3H9M7,6H17V19H7V6M9,8v9h2V8H9m4,0v9h2V8Z\" transform=\"translate(-4 -3)\"/></svg>\r\n");
      out.write("                </a>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  </div>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </tbody>\r\n");
      out.write("</table>\r\n");
      out.write(" <div id=\"div\" class=\"ml-4 font-semibold\">\r\n");
      out.write("  <a onclick=\"Inserir()\" id=\"add-more\" class=\"position color mb-6\">+ Adicionar Item</a></div>\r\n");
      out.write("    <div class=\"flex mt-3 ml-4\">\r\n");
      out.write("      <p  class=\"font-semibold text-gray-800\">Quantidade de peças:</p>\r\n");
      out.write("      \r\n");
      out.write("      <input  href=\"#\" id=\"quantidadetotal\" name=\"itensaprovados\" onblur=\"Atualizar()\"  class=\"  bg-white ml-1 text-gray-800 dark:text-white\">0\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"flex ml-4\">\r\n");
      out.write("      <p class=\"font-semibold text-gray-800\">Lucro Bruto:<p class=\"ml-1 text-gray-800 dark:text-white\">R$</p>\r\n");
      out.write("      <div  class=\"text-gray-800 dark:text-white\" id=\"vendatotal\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <div class=\"flex ml-4\">\r\n");
      out.write("  <p  class=\"font-semibold  text-gray-800\">Crédito brechozinho:<p class=\"ml-1 text-red-500\">R$</p></p>\r\n");
      out.write("  <input  id=\"valorsacola\"  class=\"flex-wrap text-red-500 bg-white\" name=\"valorcredito\">0\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"flex ml-4\">\r\n");
      out.write("  <p class=\"font-semibold  text-gray-800\">Lucro Líquido: <p class=\"ml-1 text-green-400\">R$</p></p>\r\n");
      out.write("  <input  class=\"text-green-400 bg-white\" id=\"lucroliquido\" name=\"lucroliquido\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- s \r\n");
      out.write("<div class=\"pl-5\">\r\n");
      out.write("  <p class=\"font-semibold text-2x1 text-gray-800 dark:text-white\">Caso aprovada, o valor será retirado em:</p>\r\n");
      out.write("  <div class=\"flex mt-2 mb-10\">\r\n");
      out.write("    <div class=\"items-center \">\r\n");
      out.write("      <input type=\"checkbox\" onclick=\"checkdinheiro()\" id=\"dinheiro\" name=\"credito\" class=\"items-center mb-1 checkbox \">\r\n");
      out.write("      <label for=\"aprovada\"  class=\" mt-5 text-green-700 font-semibold\">Dinheiro</label>\r\n");
      out.write("    </div>\r\n");
      out.write("<div class=\"items-center ml-4\">\r\n");
      out.write("  <input type=\"checkbox\"  onclick=\"checkcredito()\"   id=\"credito\" name=\"credito\" class=\"items-center mb-1 \">\r\n");
      out.write("  <label for=\"aprovada\"  class=\" mt-5 text-purple-700 font-semibold\">Crédito</label>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>-->\r\n");
      out.write("<div class=\"flex flex-wrap ml-3 \">\r\n");
      out.write("<button class=\"cancelarbotao bg-white hover:bg-gray-100  mr-4  block  mb-2 p-2.5 w-full z-20  text-gray-500  rounded-lg  border  border-gray-200 hover:text-gray-900 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-gray-300 dark:hover:text-white\"><a href=\"/index\" class=\"w-fulls\">Cancelar</a></button>\r\n");
      out.write("<button type=\"submit\"  class=\"ml-1 mt-5 cadastrarbotao block mr-4  mb-2 p-2.5 w-full z-20  text-gray-900  rounded-lg   border border-gray-300 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:hover:cadastrarbotaodark\"><a  onclick=\"validar()\" class=\"w-full\">Cadastrar</a></button>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<div>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/jsf/resources/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("    function checkaprovada(){\r\n");
      out.write("    var credito = document.getElementById('credito');\r\n");
      out.write("    var dinheiro = document.getElementById('dinheiro');\r\n");
      out.write("    var reprovada = document.getElementById('reprovada');\r\n");
      out.write("    var aprovada= document.getElementById('aprovada')    \r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("    if(aprovada.checked=true){\r\n");
      out.write("      reprovada.checked=false;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    else{\r\n");
      out.write("      aprovada.checked=false\r\n");
      out.write("       reprovada.checked=false\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function checkreprovada(){\r\n");
      out.write("     if(reprovada.checked=true){\r\n");
      out.write("      aprovada.checked=false;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("      dinheiro.checked=false\r\n");
      out.write("       dinheiro.checked=false\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("    </script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("  var comboGoogleTradutor = null; //Varialvel global\r\n");
      out.write("\r\n");
      out.write("  function googleTranslateElementInit() {\r\n");
      out.write("      new google.translate.TranslateElement({\r\n");
      out.write("          pageLanguage: 'pt',\r\n");
      out.write("          includedLanguages: 'pt,en',\r\n");
      out.write("          layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL\r\n");
      out.write("      }, 'google_translate_element');\r\n");
      out.write("\r\n");
      out.write("      comboGoogleTradutor = document.getElementById(\"google_translate_element\").querySelector(\".goog-te-combo\");\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function changeEvent(el) {\r\n");
      out.write("      if (el.fireEvent) {\r\n");
      out.write("          el.fireEvent('onchange');\r\n");
      out.write("      } else {\r\n");
      out.write("          var evObj = document.createEvent(\"HTMLEvents\");\r\n");
      out.write("\r\n");
      out.write("          evObj.initEvent(\"change\", false, true);\r\n");
      out.write("          el.dispatchEvent(evObj);\r\n");
      out.write("      }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function trocarIdioma(sigla) {\r\n");
      out.write("      if (comboGoogleTradutor) {\r\n");
      out.write("          comboGoogleTradutor.value = sigla;\r\n");
      out.write("          changeEvent(comboGoogleTradutor);//Dispara a troca\r\n");
      out.write("      }\r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit\"></script>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<style>\r\n");
      out.write("  \r\n");
      out.write("  table{\r\n");
      out.write("    margin-top:2%;\r\n");
      out.write("  }\r\n");
      out.write("  th{\r\n");
      out.write("    text-align:start;\r\n");
      out.write("    margin-left: 7%;\r\n");
      out.write("  }\r\n");
      out.write("  .color{\r\n");
      out.write("    color:#0bde97;\r\n");
      out.write("  }\r\n");
      out.write("  a:hover{\r\n");
      out.write("    color:#0bc889;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("input:checked{\r\n");
      out.write("  background-color: #0bde97;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("  .cadastrarbotao{\r\n");
      out.write("    \r\n");
      out.write("      margin-top: 2%;\r\n");
      out.write("      background-color: #0bde97;\r\n");
      out.write("      color: white;\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("    .cadastrarbotao:hover{\r\n");
      out.write("      background-color: #0bc889;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    @media (max-width:431px){\r\n");
      out.write("      .optionsnav{\r\n");
      out.write("        padding:0rem;\r\n");
      out.write("        margin:20%\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("@media (max-width:767px){\r\n");
      out.write("  .idiomatext{\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media(min-width:768px){\r\n");
      out.write("  nav{\r\n");
      out.write("    width:85%\r\n");
      out.write("  }\r\n");
      out.write("  body{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display:block;\r\n");
      out.write("   }\r\n");
      out.write("    \r\n");
      out.write("  table{\r\n");
      out.write("    width:80%;\r\n");
      out.write("  }\r\n");
      out.write("   .cadastrarbotao{\r\n");
      out.write("      width:13em;\r\n");
      out.write("      margin-right: 0.5%;\r\n");
      out.write("   }\r\n");
      out.write("  .cancelarbotao{\r\n");
      out.write("  width:13em;\r\n");
      out.write("  margin-top: 2%;\r\n");
      out.write("  margin-right: 0.5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".borda:focus{\r\n");
      out.write("  border-color:gray;\r\n");
      out.write("}\r\n");
      out.write(".padding{\r\n");
      out.write("  padding-top:0.70rem;\r\n");
      out.write("}\r\n");
      out.write(".login{\r\n");
      out.write("    background-color: #0bde97;\r\n");
      out.write("    margin-top: -7%;\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("  .login:hover{\r\n");
      out.write("    background-color: #0bc889;\r\n");
      out.write("  }\r\n");
      out.write("  .login a{\r\n");
      out.write("    color:white;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media (max-width:399px){\r\n");
      out.write("  .tamanho{\r\n");
      out.write("    flex-wrap: nowrap;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"../path/to/flowbite/dist/flowbite.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("  var custototal = 0;\r\n");
      out.write("  var estoquetotal=0;\r\n");
      out.write("  var lucrobruto = 0;\r\n");
      out.write("  var lucroliq =0;\r\n");
      out.write("\r\n");
      out.write("  let quantidade = document.getElementById(\"quantidade\");\r\n");
      out.write("  let valorcusto = document.getElementById(\"valorcusto\")\r\n");
      out.write("    let valorvenda = document.getElementById(\"valorvenda\");\r\n");
      out.write("    let valorsacola = document.getElementById(\"valorsacola\");\r\n");
      out.write("    let quantidadetotal =document.getElementById(\"quantidadetotal\")\r\n");
      out.write("    let vendatotal = document.getElementById(\"vendatotal\")\r\n");
      out.write("    let lucroliquido =document.getElementById(\"lucroliquido\")\r\n");
      out.write("\r\n");
      out.write("  function validar(){\r\n");
      out.write("    let nomecliente= document.getElementById(\"nomecliente\")\r\n");
      out.write("\r\n");
      out.write("    let descricao = document.getElementById(\"descricao\");\r\n");
      out.write("    let quantidade = document.getElementById(\"quantidade\");\r\n");
      out.write("    let valorcusto = document.getElementById(\"valorcusto\")\r\n");
      out.write("    let valorvenda = document.getElementById(\"valorvenda\");\r\n");
      out.write("    let valorsacola = document.getElementById(\"valorsacola\");\r\n");
      out.write("    let quantidadetotal =document.getElementById(\"quantidadetotal\")\r\n");
      out.write("    let vendatotal = document.getElementById(\"vendatotal\")\r\n");
      out.write("    let lucroliquido =document.getElementById(\"lucroliquido\")\r\n");
      out.write("    ;\r\n");
      out.write("\r\n");
      out.write("    descricao.className=\"\";\r\n");
      out.write("\r\n");
      out.write("if(nomecliente.value==''|| descricao.value=='' || quantidade.value<=0|| valorvenda.value<=0){\r\n");
      out.write("  notifier.show('Preencha todos os campos!', 'Campos em vermelho precisam ser preenchidos ', 'warning', '/src/img/danger.png', 0);\r\n");
      out.write("}\r\n");
      out.write("    if(nomecliente.value==\"\"){\r\n");
      out.write("      nomecliente.classList=\"bg-white border border-red-500 text-gray-900  rounded-lg focus:ring-red-500 focus:border-red-500 w-full p-2.5 dark:bg-gray-700 dark:border-red-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 focus:border-red-500\"\r\n");
      out.write("      alert(\"teste\")\r\n");
      out.write("    }\r\n");
      out.write("    else if(descricao.value== ''){\r\n");
      out.write("      descricao.className=\" border-1 border-r-0 roborder-1  bg-white border-red-500  text-gray-900  focus:ring-red-500 focus:border-red-500 w-full p-2.5 dark:bg-gray-700 dark:border-red-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-400 focus:border-red-500\"\r\n");
      out.write("    } \r\n");
      out.write("    else if(quantidade.value<=0){\r\n");
      out.write("     quantidade.className=\" border-1  bg-white border-red-500  text-gray-900  focus:ring-red-500 focus:border-red-500 w-full p-2.5 dark:bg-gray-700 dark:border-red-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-400 focus:border-red-500\"\r\n");
      out.write("    }\r\n");
      out.write("    else if(valorvenda.value<=0){\r\n");
      out.write("      valorvenda.className=\"negative border-1 border-l-0 bg-white border-red-500  text-gray-900   focus:ring-red-500 focus:border-red-500 w-full p-2.5 dark:bg-gray-700 dark:border-red-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-400 focus:border-red-500\"\r\n");
      out.write("    } else{\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    descricao.className=\"border-1 border-r-0 rounded-l-lg bg-white border-gray-300  text-gray-900 rounded-l-lg focus:ring-gray-400 focus:border-gray-400 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\";\r\n");
      out.write("    quantidade.className=\"border-1  bg-white border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\";\r\n");
      out.write("    valorvenda.className=\"border-1 border-r-0 bg-white border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\"\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Inserir(){\r\n");
      out.write("\r\n");
      out.write("let nomecliente= document.getElementById(\"nomecliente\")\r\n");
      out.write("let descricao = document.getElementById(\"descricao\");\r\n");
      out.write("let quantidade = document.getElementById(\"quantidade\");\r\n");
      out.write("let valorcusto = document.getElementById(\"valorcusto\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if(descricao.value=='' || quantidade.value<=0|| valorvenda.value<=0){\r\n");
      out.write("notifier.show('Preencha todos os campos!', 'Campos em vermelho precisam ser preenchidos ', 'warning', '/src/img/danger.png', 0);\r\n");
      out.write("}\r\n");
      out.write("else{\r\n");
      out.write("nomecliente.classList=\"border-1 border-r-0 rounded-l-lg bg-white border-gray-300  text-gray-900 rounded-l-lg focus:ring-gray-400 focus:border-gray-400 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\"\r\n");
      out.write("descricao.className=\"border-1 border-r-0 rounded-l-lg bg-white border-gray-300  text-gray-900 rounded-l-lg focus:ring-gray-400 focus:border-gray-400 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\";\r\n");
      out.write("quantidade.className=\"border-1  bg-white border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\";\r\n");
      out.write("valorvenda.className=\"border-1 border-r-0 bg-white border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200\"\r\n");
      out.write("\r\n");
      out.write("descricao.removeAttribute('id');\r\n");
      out.write("   quantidade.removeAttribute('id');\r\n");
      out.write("    valorcusto.removeAttribute('id');\r\n");
      out.write("    valorvenda.removeAttribute('id');\r\n");
      out.write("\r\n");
      out.write("let inserir= $(\"<tr id='tabela'><div class='flex rounded-l-lg inserir'><td><input type='text' id='descricao' class='w-1/2 border-1 border-r-0 rounded-l-lg bg-white border-gray-300  text-gray-900 rounded-l-lg focus:ring-gray-400 focus:border-gray-400 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200' placeholder='Ex: Body'></td><td><input type='number' min='1' step='.01' id='quantidade' class='border-1 border-r-0 bg-white border-gray-300  text-gray-900  focus:ring-gray-400 focus:border-gray-400 w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200' placeholder='Ex: 1'></td><td><input disabled='disabled' type='number' id='valorcusto'  class= 'border-1 border-r-0 bg-gray-100 border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200'></td><td><input type='text' id='valorvenda' onblur='Atualizar()' class='border-1 border-r-0 bg-white border-gray-300 text-gray-900   focus:ring-gray-400 focus:border-gray-400 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 focus:border-gray-200' placeholder='Ex: 8,00'></td><td><a onclick='Delete()' type='text' class='padding w-1/2 remove-item border-1 rounded-r-lg bg-white border-gray-300  text-gray-900  rounded-r-lg focus:ring-red-500 focus:border-red-500 block mr-5 p-2.5 dark:bg-gray-700 dark:border-red-600 dark:placeholder-gray-400 dark:text-white r-5'><svg  class='mb-1 w-6 h-5'id='Camada_1' data-name='Camada 1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 18'><defs><style>.cls-1{fill:#ed2121;}</style></defs><title>trash</title><path class='cls-1' d='M9,3V4H4V6H5V19a2,2,0,0,0,2,2H17a2,2,0,0,0,2-2V6h1V4H15V3H9M7,6H17V19H7V6M9,8v9h2V8H9m4,0v9h2V8Z' transform='translate(-4 -3)'/></svg></a></td></div></tr>\")\r\n");
      out.write("$(\"tbody\").append(inserir);\r\n");
      out.write("}\r\n");
      out.write(";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Atualizar(){\r\n");
      out.write("    let quantidade = document.getElementById(\"quantidade\");\r\n");
      out.write("  let valorcusto = document.getElementById(\"valorcusto\")\r\n");
      out.write("    let valorvenda = document.getElementById(\"valorvenda\");\r\n");
      out.write("    let valorsacola = document.getElementById(\"valorsacola\");\r\n");
      out.write("    let quantidadetotal =document.getElementById(\"quantidadetotal\")\r\n");
      out.write("    let vendatotal = document.getElementById(\"vendatotal\")\r\n");
      out.write("    let lucroliquido =document.getElementById(\"lucroliquido\")\r\n");
      out.write("\r\n");
      out.write("  valorcusto.value = ((valorvenda.value * quantidade.value) * 0.15) \r\n");
      out.write("    custototal+= parseFloat(valorcusto.value)\r\n");
      out.write("    estoquetotal+=parseFloat(quantidade.value)\r\n");
      out.write("    lucrobruto +=parseFloat(valorvenda.value)\r\n");
      out.write("    lucroliq +=parseFloat((valorvenda.value)- (valorcusto.value))\r\n");
      out.write("\r\n");
      out.write("    valorsacola.value = custototal;\r\n");
      out.write("    quantidadetotal.value = estoquetotal;\r\n");
      out.write("    vendatotal.value = lucrobruto;\r\n");
      out.write("    lucroliquido.innerHTML =lucroliq;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Delete(){\r\n");
      out.write("var tabela = document.getElementById(\"tabela\")\r\n");
      out.write("let quantidade = document.getElementById(\"quantidade\").value;\r\n");
      out.write("let valorvenda = document.getElementById(\"valorvenda\");\r\n");
      out.write("\r\n");
      out.write("if(descricao.value=='' || quantidade.value<=0|| valorvenda.value<=0){\r\n");
      out.write("\tvalidar()\r\n");
      out.write("\ttabela.remove()\r\n");
      out.write("\tAtualizarRemove()\r\n");
      out.write("}else{}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function AtualizarRemove(){\r\n");
      out.write("    let quantidade = document.getElementById(\"quantidade\");\r\n");
      out.write("  let valorcusto = document.getElementById(\"valorcusto\")\r\n");
      out.write("    let valorvenda = document.getElementById(\"valorvenda\");\r\n");
      out.write("    let valorsacola = document.getElementById(\"valorsacola\");\r\n");
      out.write("    let quantidadetotal =document.getElementById(\"quantidadetotal\")\r\n");
      out.write("    let vendatotal = document.getElementById(\"vendatotal\")\r\n");
      out.write("    let lucroliquido =document.getElementById(\"lucroliquido\")\r\n");
      out.write("\r\n");
      out.write("  valorcusto.value = ((valorvenda.value * quantidade.value) * 0.15) \r\n");
      out.write("    custototal-= parseFloat(valorcusto.value)\r\n");
      out.write("    estoquetotal-=parseFloat(quantidade.value)\r\n");
      out.write("    lucrobruto -=parseFloat(valorvenda.value)\r\n");
      out.write("    lucroliq -=parseFloat((valorvenda.value)- (valorcusto.value))\r\n");
      out.write("\r\n");
      out.write("    valorsacola.value = custototal;\r\n");
      out.write("    quantidadetotal.value = estoquetotal;\r\n");
      out.write("    vendatotal.value = lucrobruto;\r\n");
      out.write("    lucroliquido.value =lucroliq;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("    ///Volta o input para cor normal\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("       // Create a function to change\r\n");
      out.write("    // the hash value of the page\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("////////////////\r\n");
      out.write("// TEMA DARK\r\n");
      out.write("  // On page load or when changing themes, best to add inline in `head` to avoid FOUC\r\n");
      out.write("  if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {\r\n");
      out.write("      document.documentElement.classList.add('dark');\r\n");
      out.write("  } else {\r\n");
      out.write("      document.documentElement.classList.remove('dark')\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');\r\n");
      out.write("var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');\r\n");
      out.write("\r\n");
      out.write("// Change the icons inside the button based on previous settings\r\n");
      out.write("if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {\r\n");
      out.write("    themeToggleLightIcon.classList.remove('hidden');\r\n");
      out.write("} else {\r\n");
      out.write("    themeToggleDarkIcon.classList.remove('hidden');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var themeToggleBtn = document.getElementById('theme-toggle');\r\n");
      out.write("\r\n");
      out.write("themeToggleBtn.addEventListener('click', function() {\r\n");
      out.write("\r\n");
      out.write("    // toggle icons inside button\r\n");
      out.write("    themeToggleDarkIcon.classList.toggle('hidden');\r\n");
      out.write("    themeToggleLightIcon.classList.toggle('hidden');\r\n");
      out.write("\r\n");
      out.write("    // if set via local storage previously\r\n");
      out.write("    if (localStorage.getItem('color-theme')) {\r\n");
      out.write("        if (localStorage.getItem('color-theme') === 'light') {\r\n");
      out.write("            document.documentElement.classList.add('dark');\r\n");
      out.write("            localStorage.setItem('color-theme', 'dark');\r\n");
      out.write("        } else {\r\n");
      out.write("            document.documentElement.classList.remove('dark');\r\n");
      out.write("            localStorage.setItem('color-theme', 'light');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    // if NOT set via local storage previously\r\n");
      out.write("    } else {\r\n");
      out.write("        if (document.documentElement.classList.contains('dark')) {\r\n");
      out.write("            document.documentElement.classList.remove('dark');\r\n");
      out.write("            localStorage.setItem('color-theme', 'light');\r\n");
      out.write("        } else {\r\n");
      out.write("            document.documentElement.classList.add('dark');\r\n");
      out.write("            localStorage.setItem('color-theme', 'dark');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("  <script>\r\n");
      out.write("if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {\r\n");
      out.write("    document.documentElement.classList.add('dark');\r\n");
      out.write("} else {\r\n");
      out.write("    document.documentElement.classList.remove('dark')\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');\r\n");
      out.write("var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');\r\n");
      out.write("\r\n");
      out.write("//Change the icons inside the button based on previous settings\r\n");
      out.write("if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {\r\n");
      out.write("  themeToggleLightIcon.classList.remove('hidden');\r\n");
      out.write("} else {\r\n");
      out.write("  themeToggleDarkIcon.classList.remove('hidden');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var themeToggleBtn = document.getElementById('theme-toggle');\r\n");
      out.write("\r\n");
      out.write("themeToggleBtn.addEventListener('click', function() {\r\n");
      out.write("\r\n");
      out.write("  // toggle icons inside button\r\n");
      out.write("  themeToggleDarkIcon.classList.toggle('hidden');\r\n");
      out.write("  themeToggleLightIcon.classList.toggle('hidden');\r\n");
      out.write("\r\n");
      out.write("  // if set via local storage previously\r\n");
      out.write("  if (localStorage.getItem('color-theme')) {\r\n");
      out.write("      if (localStorage.getItem('color-theme') === 'light') {\r\n");
      out.write("          document.documentElement.classList.add('dark');\r\n");
      out.write("          localStorage.setItem('color-theme', 'dark');\r\n");
      out.write("      } else {\r\n");
      out.write("          document.documentElement.classList.remove('dark');\r\n");
      out.write("          localStorage.setItem('color-theme', 'light');\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("  // if NOT set via local storage previously\r\n");
      out.write("  } else {\r\n");
      out.write("      if (document.documentElement.classList.contains('dark')) {\r\n");
      out.write("          document.documentElement.classList.remove('dark');\r\n");
      out.write("          localStorage.setItem('color-theme', 'light');\r\n");
      out.write("      } else {\r\n");
      out.write("          document.documentElement.classList.add('dark');\r\n");
      out.write("          localStorage.setItem('color-theme', 'dark');\r\n");
      out.write("      }\r\n");
      out.write("  }\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
