package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastrocliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Cadastro de Cliente</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-50 dark:bg-gray-800\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouttopo.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"flex pl-5 pt-5\" aria-label=\"Breadcrumb\">\r\n");
      out.write("    <ol class=\"inline-flex items-center space-x-1 md:space-x-3\">\r\n");
      out.write("      <li class=\"inline-flex items-center\">\r\n");
      out.write("        <a href=\"/index\" class=\"inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white\">\r\n");
      out.write("          <svg class=\"w-4 h-4 mr-2\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z\"></path></svg>\r\n");
      out.write("          Página Inicial\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <svg class=\"w-6 h-6 text-gray-400\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z\" clip-rule=\"evenodd\"></path></svg>\r\n");
      out.write("          <a href=\"/clientes\" class=\"ml-1 text-sm font-medium text-gray-700 hover:text-gray-900 md:ml-2 dark:text-gray-400 dark:hover:text-white\">Clientes</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <svg class=\"w-6 h-6 text-gray-400\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z\" clip-rule=\"evenodd\"></path></svg>\r\n");
      out.write("          <a href=\"/cadastracliente\" class=\"ml-1 text-sm font-medium text-gray-700 hover:text-gray-900 md:ml-2 dark:text-gray-400 dark:hover:text-white\">Cadastrar Clientes</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ol>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"bg-white m-5 dark:bg-gray-700\" \">\r\n");
      out.write("  <div class=\"flex justify-between items-end responsividade\">\r\n");
      out.write("  <h1 class=\"flex pl-4 pt-5 text-4xl font-semibold dark:text-white\">Cliente</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <!-- forms -->\r\n");
      out.write("<form method=\"POST\" action=\"/cadastrarcliente\" accept-charset=\"UTF-8\">\r\n");
      out.write("    <h2 class=\"flex pl-4 pt-5 text-xl text-gray-400\">Dados Cadastrais</h2>\r\n");
      out.write("    <div class=\"pl-4 pt-5 pr-4 grid gap-6 mb-6 md:grid-cols-3\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">Nome Completo</label>\r\n");
      out.write("            <input type=\"text\" id=\"nome\" name=\"nome\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"Ex: Maria Pereira\" required >\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">CPF</label>\r\n");
      out.write("            <input type=\"text\" id=\"cpf\" name=\"cpf\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"000.000.000-00\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pr-2\">\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">E-mail</label>\r\n");
      out.write("            <input type=\"text\" id=\"email\" name=\"email\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"mariapereira@hotmail.com\" >\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">Telefone</label>\r\n");
      out.write("            <input type=\"text\" id=\"telefone\" name=\"telefone\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"(00) 00000-0000\" >\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">Celular</label>\r\n");
      out.write("            <input type=\"text\" id=\"celular\" name=\"celular\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"(00) 00000-0000\" >\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pr-2\">\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400\">Conheceu a loja por</label>\r\n");
      out.write("            <select name=\"option\"  class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\">\r\n");
      out.write("            <option selected>Escolha uma opção</option>\r\n");
      out.write("            <option value=\"Indicação\">Indicação</option>\r\n");
      out.write("            <option value=\"Facebook\">Facebook</option>\r\n");
      out.write("            <option value=\"Instagram\">Instagram</option>\r\n");
      out.write("            <option value=\"Outros\">Outros</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <h2 class=\"flex pl-5 pt-5 text-xl text-gray-400\">Endereço</h2>\r\n");
      out.write("    <div class=\"pl-5 pt-5 pr-5 grid gap-6 mb-6 md:grid-cols-3 mr-4 pb-5\">\r\n");
      out.write("                  <div >\r\n");
      out.write("                <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">CEP</label>\r\n");
      out.write("                    <input type=\"search\" id=\"cep\" name=\"cep\" value=\"\" size=\"10\" maxlength=\"9\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \" placeholder=\"CEP\" onblur=\"pesquisacep(this.value)\";>\r\n");
      out.write("              </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <label for=\"countries\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400\">Estado</label>\r\n");
      out.write("                <input id=\"uf\" name=\"uf\" class=\" bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">Cidade</label>\r\n");
      out.write("                <input type=\"text\" id=\"cidade\" name=\"cidade\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"Ex: Matão\" >\r\n");
      out.write("            </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">Rua</label>\r\n");
      out.write("            <input type=\"text\" id=\"rua\" name=\"rua\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"Ex.: Rua ABC\" >\r\n");
      out.write("        </div>\r\n");
      out.write("        <div >\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">Número</label>\r\n");
      out.write("            <input type=\"text\" id=\"numero\" name=\"numero\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500\" placeholder=\"1234\" >\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <label class=\"block mb-2 text-sm font-medium text-black dark:text-gray-300\">Bairro</label>\r\n");
      out.write("            <input type=\"text\" id=\"bairro\" name=\"bairro\" class=\"bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-400 focus:border-gray-200 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-500\" placeholder=\"District Name\" >\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"flex pt-5\">\r\n");
      out.write("          <button class=\" ml-1 mt-5 cancelarbotao bg-transparent hover:bg-gray-200  block  mb-2 p-2.5 w-full z-20 text-sm text-gray-900  rounded-lg  border border border-gray-300 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:hover:bg-gray-600 mr-1\">Cancelar</button>\r\n");
      out.write("\r\n");
      out.write("          <button id=\"btn-nt-show\" type=\"submit\" class=\" flex-wrap block cadastrarbotao 0 mt-1 mb-2 p-2.5 w-full z-20 text-sm text-gray-900  rounded-lg  focus:ring-gray-400 \">Cadastrar</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("  <footer class=\"leading-normal tracking-normal text-white gradient\" style=\"font-family: 'Source Sans Pro', sans-serif;\">\r\n");
      out.write("<svg class=\"wave-top\" viewBox=\"0 0 1439 147\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\r\n");
      out.write("  <g stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\">\r\n");
      out.write("    <g transform=\"translate(-1.000000, -14.000000)\" fill-rule=\"nonzero\">\r\n");
      out.write("      <g class=\"wave\" fill=\"#f8fafc\">\r\n");
      out.write("        <path\r\n");
      out.write("          d=\"M1440,84 C1383.555,64.3 1342.555,51.3 1317,45 C1259.5,30.824 1206.707,25.526 1169,22 C1129.711,18.326 1044.426,18.475 980,22 C954.25,23.409 922.25,26.742 884,32 C845.122,37.787 818.455,42.121 804,45 C776.833,50.41 728.136,61.77 713,65 C660.023,76.309 621.544,87.729 584,94 C517.525,105.104 484.525,106.438 429,108 C379.49,106.484 342.823,104.484 319,102 C278.571,97.783 231.737,88.736 205,84 C154.629,75.076 86.296,57.743 0,32 L0,0 L1440,0 L1440,84 Z\"\r\n");
      out.write("        ></path>\r\n");
      out.write("      </g>\r\n");
      out.write("      <g transform=\"translate(1.000000, 15.000000)\" fill=\"#FFFFFF\">\r\n");
      out.write("        <g transform=\"translate(719.500000, 68.500000) rotate(-180.000000) translate(-719.500000, -68.500000) \">\r\n");
      out.write("          <path d=\"M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496\" opacity=\"0.100000001\"></path>\r\n");
      out.write("          <path\r\n");
      out.write("            d=\"M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z\"\r\n");
      out.write("            opacity=\"0.100000001\"\r\n");
      out.write("          ></path>\r\n");
      out.write("          <path d=\"M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z\" opacity=\"0.200000003\"></path>\r\n");
      out.write("        </g>\r\n");
      out.write("      </g>\r\n");
      out.write("    </g>\r\n");
      out.write("  </g>\r\n");
      out.write("</svg>\r\n");
      out.write("<section class=\" mt-5 text-center lg:text-left  text-white\">\r\n");
      out.write("  <div class=\"mx-6 pt-5 py-10 text-center md:text-left\">\r\n");
      out.write("    <div class=\"grid grid-1 md:grid-cols-2 lg:grid-cols-4 gap-8 pb-5\">\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <h6 class=\"\r\n");
      out.write("            flex\r\n");
      out.write("            items-center\r\n");
      out.write("            justify-center\r\n");
      out.write("            md:justify-start\r\n");
      out.write("            negativemargin\r\n");
      out.write("          \">\r\n");
      out.write("        <img class=\"tamanhoimg\"src=\"/src/log.png\">\r\n");
      out.write("        </h6>\r\n");
      out.write("        <p class=\"font-semibold ml-4 negativemargin\">\r\n");
      out.write("          Importados & Brechó Infantil \r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <h6 class=\"uppercase font-semibold mb-4 flex justify-center md:justify-start\">\r\n");
      out.write("          Produtos\r\n");
      out.write("        </h6>\r\n");
      out.write("        <p class=\"mb-4\">\r\n");
      out.write("          <a href=\"#!\" class=\"text-white\">Lista</a>\r\n");
      out.write("        </p>\r\n");
      out.write("        <p class=\"mb-4\">\r\n");
      out.write("          <a href=\"#!\" class=\"text-white\">Cadastrar</a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <h6 class=\"uppercase font-semibold mb-4 flex justify-center md:justify-start\">\r\n");
      out.write("          Clientes\r\n");
      out.write("        </h6>\r\n");
      out.write("        <p class=\"mb-4\">\r\n");
      out.write("          <a href=\"#!\" class=\"text-white\">Lista</a>\r\n");
      out.write("        </p>\r\n");
      out.write("        <p class=\"mb-4\">\r\n");
      out.write("          <a href=\"#!\" class=\"text-white\">Cadastrar</a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <h6 class=\"uppercase font-semibold mb-4 flex justify-center md:justify-start\">\r\n");
      out.write("          Avaliação\r\n");
      out.write("        </h6>\r\n");
      out.write("        <p class=\"mb-4\">\r\n");
      out.write("          <a href=\"#!\" class=\"text-white\">Lista</a>\r\n");
      out.write("        </p>\r\n");
      out.write("        <p class=\"mb-4\">\r\n");
      out.write("          <a href=\"#!\" class=\"text-white\">Cadastrar</a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>  \r\n");
      out.write("  </div>\r\n");
      out.write("</section> \r\n");
      out.write("</footer>\r\n");
      out.write("<script>\r\n");
      out.write("    function limpa_formulário_cep() {\r\n");
      out.write("      //Limpa valores do formulário de cep.\r\n");
      out.write("      document.getElementById('rua').value = (\"\");\r\n");
      out.write("      document.getElementById('bairro').value = (\"\");\r\n");
      out.write("      document.getElementById('cidade').value = (\"\");\r\n");
      out.write("      document.getElementById('uf').value = (\"\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function meu_callback(conteudo) {\r\n");
      out.write("      if (!(\"erro\" in\r\n");
      out.write("        conteudo)) {\r\n");
      out.write("        //Atualiza os campos com os valores.\r\n");
      out.write("        document.getElementById('rua').value = (conteudo.logradouro);\r\n");
      out.write("        document.getElementById('bairro').value = (conteudo.bairro);\r\n");
      out.write("        document.getElementById('cidade').value = (conteudo.localidade);\r\n");
      out.write("        document.getElementById('uf').value = (conteudo.uf);\r\n");
      out.write("      } //end if.\r\n");
      out.write("      else {\r\n");
      out.write("        //CEP não Encontrado.\r\n");
      out.write("        limpa_formulário_cep();\r\n");
      out.write("        alert(\"CEP não encontrado.\");\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function pesquisacep(valor) {\r\n");
      out.write("\r\n");
      out.write("      //Nova variável \"cep\" somente com dígitos.\r\n");
      out.write("      var cep = valor.replace(/\\D/g, '');\r\n");
      out.write("\r\n");
      out.write("      //Verifica se campo cep possui valor informado.\r\n");
      out.write("      if (cep != \"\") {\r\n");
      out.write("\r\n");
      out.write("        //Expressão regular para validar o CEP.\r\n");
      out.write("        var validacep = /^[0-9]{8}$/;\r\n");
      out.write("\r\n");
      out.write("        //Valida o formato do CEP.\r\n");
      out.write("        if (validacep.test(cep)) {\r\n");
      out.write("\r\n");
      out.write("          //Preenche os campos com \"...\" enquanto consulta webservice.\r\n");
      out.write("          document.getElementById('rua').value = \"...\";\r\n");
      out.write("          document.getElementById('bairro').value = \"...\";\r\n");
      out.write("          document.getElementById('cidade').value = \"...\";\r\n");
      out.write("          document.getElementById('uf').value = \"...\";\r\n");
      out.write("\r\n");
      out.write("          //Cria um elemento javascript.\r\n");
      out.write("          var script = document.createElement('script');\r\n");
      out.write("\r\n");
      out.write("          //Sincroniza com o callback.\r\n");
      out.write("          script.src = 'https://viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';\r\n");
      out.write("\r\n");
      out.write("          //Insere script no documento e carrega o conteúdo.\r\n");
      out.write("          document.body.appendChild(script);\r\n");
      out.write("\r\n");
      out.write("        } //end if.\r\n");
      out.write("        else {\r\n");
      out.write("          //cep é inválido.\r\n");
      out.write("          limpa_formulário_cep();\r\n");
      out.write("          notifier.show('Formato de CEP inválido!', 'Campos em vermeho ', 'danger', '/src/img/danger.png', 0);\r\n");
      out.write("        }\r\n");
      out.write("      } //end if.\r\n");
      out.write("      else {\r\n");
      out.write("        //cep sem valor, limpa formulário.\r\n");
      out.write("        limpa_formulário_cep();\r\n");
      out.write("      }\r\n");
      out.write("      ///validar\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ///// VALIDAÇÃO FORMULÁRIO///\r\n");
      out.write("    const nome = document.getElementById(\"nome\")\r\n");
      out.write("    const cpf = document.getElementById(\"cpf\")\r\n");
      out.write("    const email = document.getElementById(\"email\")\r\n");
      out.write("    const telefone = document.getElementById(\"telefone\")\r\n");
      out.write("    const celular = document.getElementById(\"celular\")\r\n");
      out.write("    const cep = document.getElementById(\"cep\")\r\n");
      out.write("    const cidade = document.getElementById(\"cidade\")\r\n");
      out.write("    const rua = document.getElementById(\"rua\")\r\n");
      out.write("    const numero = document.getElementById(\"numero\")\r\n");
      out.write("    const uf = document.getElementById(\"uf\")\r\n");
      out.write("    const bairro = document.getElementById(\"bairro\")\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function validar() {\r\n");
      out.write("      if (nome.value == '') {\r\n");
      out.write("        notifier.show('Preencha todos os campos!', 'Campos em vermeho ', 'danger', '/src/img/danger.png', 0);\r\n");
      out.write("        nome.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (cpf.value == '') {\r\n");
      out.write("        cpf.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (email.value == '') {\r\n");
      out.write("        email.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        email.focus()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (telefone.value == '') {\r\n");
      out.write("        telefone.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        telefone.focus()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (celular.value == '') {\r\n");
      out.write("        celular.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        celular.focus()\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if (cep.value == '') {\r\n");
      out.write("        cep.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        cep.focus()\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if (uf.value == '') {\r\n");
      out.write("        uf.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        uf.focus()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (cidade.value == '') {\r\n");
      out.write("        cidade.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        cidade.focus()\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (rua.value == '') {\r\n");
      out.write("        rua.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        rua.focus()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (numero.value == '') {\r\n");
      out.write("        numero.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        numero.focus()\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      if (bairro.value == '') {\r\n");
      out.write("        bairro.className = \"negative bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-400 dark:focus:b-gray-2lue-500 \";\r\n");
      out.write("        bairro.focus()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      } else {\r\n");
      out.write("        window.location(\"/index\")\r\n");
      out.write("        notifier.show('Cliente Cadastrado com sucesso!', '', 'success', '/src/check-mark-img.png', 0);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".tamanhoimg{\r\n");
      out.write("  width: 40%;\r\n");
      out.write("}\r\n");
      out.write(".negativemargin{\r\n");
      out.write("  margin-top: -4%;\r\n");
      out.write("}\r\n");
      out.write(" .input{\r\n");
      out.write("    width:31%;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("      .cadastrarbotao{\r\n");
      out.write("    width:13em;\r\n");
      out.write("    margin-top: 2%;\r\n");
      out.write("    background-color: #0bde97;\r\n");
      out.write("    color: white;\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("  .cadastrarbotao:hover{\r\n");
      out.write("    background-color: #0bc889;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".cancelarbotao{\r\n");
      out.write("    width:13em;\r\n");
      out.write("    margin-top: 2%;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
